//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://directsupply.com/services/cart", ConfigurationName="IGetCart")]
public interface IGetCart
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/cart/IGetCart/GetCart", ReplyAction="http://directsupply.com/services/cart/IGetCart/GetCartResponse")]
    DS.DataContracts.Responses.CartResponse GetCart(DS.DataContracts.Requests.CartRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/cart/IGetCart/GetCart", ReplyAction="http://directsupply.com/services/cart/IGetCart/GetCartResponse")]
    System.Threading.Tasks.Task<DS.DataContracts.Responses.CartResponse> GetCartAsync(DS.DataContracts.Requests.CartRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGetCartChannel : IGetCart, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCartClient : System.ServiceModel.ClientBase<IGetCart>, IGetCart
{
    
    public GetCartClient()
    {
    }
    
    public GetCartClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetCartClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetCartClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetCartClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DS.DataContracts.Responses.CartResponse GetCart(DS.DataContracts.Requests.CartRequest request)
    {
        return base.Channel.GetCart(request);
    }
    
    public System.Threading.Tasks.Task<DS.DataContracts.Responses.CartResponse> GetCartAsync(DS.DataContracts.Requests.CartRequest request)
    {
        return base.Channel.GetCartAsync(request);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://directsupply.com/services/cart", ConfigurationName="ICreateCart")]
public interface ICreateCart
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/cart/ICreateCart/CreateCart", ReplyAction="http://directsupply.com/services/cart/ICreateCart/CreateCartResponse")]
    DS.DataContracts.Responses.CartResponse CreateCart();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/cart/ICreateCart/CreateCart", ReplyAction="http://directsupply.com/services/cart/ICreateCart/CreateCartResponse")]
    System.Threading.Tasks.Task<DS.DataContracts.Responses.CartResponse> CreateCartAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICreateCartChannel : ICreateCart, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CreateCartClient : System.ServiceModel.ClientBase<ICreateCart>, ICreateCart
{
    
    public CreateCartClient()
    {
    }
    
    public CreateCartClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CreateCartClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CreateCartClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CreateCartClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DS.DataContracts.Responses.CartResponse CreateCart()
    {
        return base.Channel.CreateCart();
    }
    
    public System.Threading.Tasks.Task<DS.DataContracts.Responses.CartResponse> CreateCartAsync()
    {
        return base.Channel.CreateCartAsync();
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://directsupply.com/services/cart", ConfigurationName="IAddProduct")]
public interface IAddProduct
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/cart/IAddProduct/AddProduct", ReplyAction="http://directsupply.com/services/cart/IAddProduct/AddProductResponse")]
    DS.DataContracts.Responses.CartResponse AddProduct(DS.DataContracts.Requests.CartProductRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/cart/IAddProduct/AddProduct", ReplyAction="http://directsupply.com/services/cart/IAddProduct/AddProductResponse")]
    System.Threading.Tasks.Task<DS.DataContracts.Responses.CartResponse> AddProductAsync(DS.DataContracts.Requests.CartProductRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAddProductChannel : IAddProduct, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AddProductClient : System.ServiceModel.ClientBase<IAddProduct>, IAddProduct
{
    
    public AddProductClient()
    {
    }
    
    public AddProductClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AddProductClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AddProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AddProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DS.DataContracts.Responses.CartResponse AddProduct(DS.DataContracts.Requests.CartProductRequest request)
    {
        return base.Channel.AddProduct(request);
    }
    
    public System.Threading.Tasks.Task<DS.DataContracts.Responses.CartResponse> AddProductAsync(DS.DataContracts.Requests.CartProductRequest request)
    {
        return base.Channel.AddProductAsync(request);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://directsupply.com/services/cart", ConfigurationName="IRemoveProduct")]
public interface IRemoveProduct
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/cart/IRemoveProduct/RemoveProduct", ReplyAction="http://directsupply.com/services/cart/IRemoveProduct/RemoveProductResponse")]
    DS.DataContracts.Responses.CartResponse RemoveProduct(DS.DataContracts.Requests.CartProductRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/cart/IRemoveProduct/RemoveProduct", ReplyAction="http://directsupply.com/services/cart/IRemoveProduct/RemoveProductResponse")]
    System.Threading.Tasks.Task<DS.DataContracts.Responses.CartResponse> RemoveProductAsync(DS.DataContracts.Requests.CartProductRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRemoveProductChannel : IRemoveProduct, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RemoveProductClient : System.ServiceModel.ClientBase<IRemoveProduct>, IRemoveProduct
{
    
    public RemoveProductClient()
    {
    }
    
    public RemoveProductClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RemoveProductClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoveProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoveProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DS.DataContracts.Responses.CartResponse RemoveProduct(DS.DataContracts.Requests.CartProductRequest request)
    {
        return base.Channel.RemoveProduct(request);
    }
    
    public System.Threading.Tasks.Task<DS.DataContracts.Responses.CartResponse> RemoveProductAsync(DS.DataContracts.Requests.CartProductRequest request)
    {
        return base.Channel.RemoveProductAsync(request);
    }
}
