//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://directsupply.com/services/product", ConfigurationName="IGetProducts")]
public interface IGetProducts
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/product/IGetProducts/GetProducts", ReplyAction="http://directsupply.com/services/product/IGetProducts/GetProductsResponse")]
    DS.DataContracts.Responses.ProductResponse GetProducts(DS.DataContracts.Requests.ProductRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://directsupply.com/services/product/IGetProducts/GetProducts", ReplyAction="http://directsupply.com/services/product/IGetProducts/GetProductsResponse")]
    System.Threading.Tasks.Task<DS.DataContracts.Responses.ProductResponse> GetProductsAsync(DS.DataContracts.Requests.ProductRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGetProductsChannel : IGetProducts, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetProductsClient : System.ServiceModel.ClientBase<IGetProducts>, IGetProducts
{
    
    public GetProductsClient()
    {
    }
    
    public GetProductsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetProductsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetProductsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetProductsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DS.DataContracts.Responses.ProductResponse GetProducts(DS.DataContracts.Requests.ProductRequest request)
    {
        return base.Channel.GetProducts(request);
    }
    
    public System.Threading.Tasks.Task<DS.DataContracts.Responses.ProductResponse> GetProductsAsync(DS.DataContracts.Requests.ProductRequest request)
    {
        return base.Channel.GetProductsAsync(request);
    }
}
